### ISSUE TITLE
Change Code block to dart code

### ISSUE THREAD

**Issue by happyharis** [erluxman/awesomefluttertips#14]
Make use [syntax highlighting](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting) using a specific language.

How to use: 
```
```dart
code block
` ``
```

Before 
```
// Without the ```code_language
final name = 'Haris';
```

After 
```dart
// With the ```code_language
final name = 'Haris';
```

**Comment by erluxman** [comment]
This is a really really amazing suggestion. I didn't know this.

Will do it Thanks a lot.
