### ISSUE TITLE
Making pages of 20 items instead of just 7.

### ISSUE THREAD

**Issue by erluxman** [erluxman/awesomefluttertips#18]
One of the aspects I liked about putting all tips in a single page was that I could just keep scroll without navigation.

Now it needs action from the reader which is an additional burden that will reduce the average consumption amount.

I am not sure if anybody is seeing issues in this repo (please put some reaction if you do, just to let me know that you see them), but I would want to discuss this before making change.

20 tips a  page is the sweet spot I think will have a good enough loading time and the continuous supply of tips in a single Page.

**Comment by cyberhck** [comment]
How about an infinite scroll with chunk size of 20 items? If you're concerned about user having to interact...

**Comment by erluxman** [comment]
How to do that in markdown? I didn't know that was possible

**Comment by rebootcode** [comment]
15 a page?

**Comment by erluxman** [comment]
Yeah, 15 or 20 it's the almost same thing. What I mean is shall I change the format?

**Comment by rebootcode** [comment]
Yes, also do you have email address -if you are available for hire?

**Comment by erluxman** [comment]
erluxman@gmail.com or we can talk in twitter at @erluxman

**Comment by cyberhck** [comment]
only md wouldn't work, you could however use jekyll to turn your md into actual pages, and it'll be hosted on erluxman.github.io/awesomefluttertips that way you can do whatever you want :) I haven't used jekyll in a while, but I'm sure there's an existing template for that,

**Comment by cyberhck** [comment]
https://github.com/tobiasahlin/infinite-jekyll this might be a nice plugin, however someone else with better experience might be able to help better

**Comment by erluxman** [comment]
Will look into it. I want to keep this repo as vanilla as possible. I have hosted my site on something like that and there are issues of epub size exceeding 100 MB and Github pages not yet supporting Github LFS.

**Comment by cyberhck** [comment]
No, these are light weight static files, there's neither epub or size being more than couple of megabytes,

**Comment by erluxman** [comment]
Interesting..

**Comment by narwhal3301** [comment]
If you think you have it -- https://narwhal3301.github.io/

**Comment by erluxman** [comment]
Ok, will go for 20 tips for page. Will do the refactoring this weekend.
