### ISSUE TITLE
Images inside examples are too big

### ISSUE THREAD

**Issue by Tamir198** [erluxman/awesomefluttertips#22]
**Generally** - when you are using an image (or GIF) you can control the size of the image so it won't be too big (as for the moment its kind of too big).

Example:

-     <img src="your image link" height="450">

-     <img src="your image link" width="450">

You can also use both height and width together 

-     <img src="your image link" height="450" width="450">

**Comment by Tamir198** [comment]
Update - I have opened [Pull request](https://github.com/erluxman/awesomefluttertips/pull/23)  as an example of how to resize the images

**Comment by erluxman** [comment]
Merged

**Comment by Tamir198** [comment]
Update - I have created one pull request for every page that I have made some change.

This way, if I made some mistake in one of the pages accidentally it won't affect the rest of them.

@erluxman
