### ISSUE TITLE
Addition of Enum extensions

### ISSUE THREAD

**Issue by abhishekwl** [erluxman/awesomefluttertips#3]
A powerful but not very well known feature.
Allows for custom function prototypes to be defined for Enumeration types. Can be very useful in situations such as getting the value of an enumeration type in string. Check out this [link](https://stackoverflow.com/a/59308734) for an example.

**Comment by erluxman** [comment]
Will look into it.

**Comment by edufolly** [comment]
@abhishekwl Nice!! A loved it.

**Comment by erluxman** [comment]
Added this tips : 

https://github.com/erluxman/awesomefluttertips/blob/master/week11.md#day74-enum-values
